{
   "no_index" : {
      "directory" : [
         "t",
         "inc"
      ]
   },
   "meta-spec" : {
      "version" : 1.4,
      "url" : "http://module-build.sourceforge.net/META-spec-v1.4.html"
   },
   "generated_by" : "ExtUtils::MakeMaker version 6.54",
   "distribution_type" : "module",
   "version" : "1.44",
   "name" : "PApp",
   "author" : [],
   "license" : "unknown",
   "build_requires" : {
      "ExtUtils::MakeMaker" : 0
   },
   "requires" : {
      "XML::Sablotron" : "1.0100001",
      "URI" : 1.22,
      "Digest::SHA1" : 1.01,
      "Guard" : 1,
      "Compress::LZF" : 1,
      "Storable" : 2.05,
      "JSON::XS" : 2.01,
      "Crypt::Twofish2" : 0.01,
      "MIME::Base64" : 0,
      "PApp::SQL" : 0.143,
      "DBD::mysql" : 2.04,
      "String::Similarity" : 0.02,
      "common::sense" : 0,
      "XML::Parser" : 2.31,
      "Convert::Scalar" : 1.02,
      "DBI" : 1.3
   },
   "abstract" : null,
   "configure_requires" : {
      "ExtUtils::MakeMaker" : 0
   }
}
