# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PApp
version:      0.95
version_from: PApp.pm
installdirs:  site
requires:
    Compress::LZF:                 0.1045
    Convert::Scalar:               0.1
    Crypt::Twofish2:               0.01
    DBD::mysql:                    2.04
    DBI:                           1.3
    Digest::SHA1:                  1.01
    PApp::SQL:                     0.142
    Storable:                      2.05
    String::Similarity:            0.02
    URI:                           1.22
    XML::Parser:                   2.31
    XML::Sablotron:                0.98

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
