#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PApp
version:      0.22
version_from: PApp.pm
installdirs:  site
requires:
    XML::Sablotron:                0.98
    URI:                           1.22
    Digest::SHA1:                  1.01
    Compress::LZF:                 0.1045
    Storable:                      2.05
    Crypt::Twofish2:               0.01
    PApp::SQL:                     0.142
    DBD::mysql:                    2.04
    String::Similarity:            0.02
    XML::Parser:                   2.31
    DBI:                           1.3
    Convert::Scalar:               0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
