--- #YAML:1.0
name:                PApp
version:             1.43
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Compress::LZF:                 1
    Convert::Scalar:               1.02
    Crypt::Twofish2:               0.01
    DBD::mysql:                    2.04
    DBI:                           1.3
    Digest::SHA1:                  1.01
    JSON::XS:                      2.01
    PApp::SQL:                     0.143
    Storable:                      2.05
    String::Similarity:            0.02
    URI:                           1.22
    XML::Parser:                   2.31
    XML::Sablotron:                1.0100001
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
